const BASE_URL=window.location.hostname==='localhost'&&window.location.port!=='8080'?'http://localhost:8080':window.location.origin;
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}
function safeImageUrl(value){if(!value)return'';try{const url=new URL(String(value),window.location.origin);return['http:','https:','blob:'].includes(url.protocol)?url.href:''}catch{return''}}
const $=id=>document.getElementById(id),token=()=>localStorage.getItem('token'),authHeaders=()=>({Authorization:`Bearer ${token()}`});
const params=new URLSearchParams(window.location.search),personID=Number(params.get('PersonID'));let familyTreeCode=params.get('familyTreeCode')||sessionStorage.getItem('familyTreeCode')||'',cousinGeneration=Number(sessionStorage.getItem('familyTreeCousinGeneration')||1);if(!Number.isInteger(cousinGeneration)||cousinGeneration<1||cousinGeneration>6)cousinGeneration=1;
function nameOf(p){if(!p)return'';const first=[p.FirstName,p.MiddleName,p.SuffixName].filter(Boolean).join(' ');let n=[p.LastName?`${p.LastName},`:'',first].filter(Boolean).join(' ').trim();const extra=[p.NickName,p.MaidenName].filter(Boolean).join(' ');if(extra)n+=` (${extra})`;return n}
function isDeceased(p){return Boolean(p&&(Number(p.Died)===1||p.DeathDate))}function ageOf(p){if(!p||!p.BirthDate)return'';const b=new Date(`${String(p.BirthDate).slice(0,10)}T00:00:00`),e=p.DeathDate?new Date(`${String(p.DeathDate).slice(0,10)}T00:00:00`):new Date();let a=e.getFullYear()-b.getFullYear(),m=e.getMonth()-b.getMonth();if(m<0||(m===0&&e.getDate()<b.getDate()))a--;return a>=0?a:''}
function lifespan(p){if(!p)return'';const b=p.BirthDate?String(p.BirthDate).slice(0,4):'';const d=p.DeathDate?String(p.DeathDate).slice(0,4):(Number(p.Died)?'':'Living');if(!b&&!d)return'';return `${b||'?'}–${d||'?'}`}
function homeOf(p){return[p&&p.CurrentCity,p&&p.CurrentState].filter(Boolean).join(', ')}
function openPerson(id){location.href=`FTPerson.html?PersonID=${encodeURIComponent(id)}&familyTreeCode=${encodeURIComponent(familyTreeCode)}`}
function makeFocus(id){location.href=`FTAncestor.html?PersonID=${encodeURIComponent(id)}&familyTreeCode=${encodeURIComponent(familyTreeCode)}`}
function card(p,isFocus=false){if(!p)return'<div class="ancestor-card empty"></div>';const photo=p.ProfileImageUrl?safeImageUrl(p.ProfileImageUrl):'images/person-placeholder.svg';return `<div class="ancestor-card"><img class="photo" src="${escapeHtml(photo)}" alt="${escapeHtml(nameOf(p))}"><div class="name">${escapeHtml(nameOf(p))}</div><div class="meta">${escapeHtml(lifespan(p))}</div><div class="meta">${escapeHtml(homeOf(p))}</div><div class="icon-row"><button class="icon-action person-link" data-id="${p.PersonID}" type="button" title="View Person" aria-label="View Person"><img src="images/person.svg" alt=""></button><button class="icon-action tree-link" data-id="${p.PersonID}" type="button" title="${isFocus?'Current Tree Person':'View Ancestor Tree'}" aria-label="${isFocus?'Current Tree Person':'View Ancestor Tree'}" ${isFocus?'disabled':''}><img src="images/tree.svg" alt=""></button></div></div>`}
function personTableRow(p){const photo=p.ProfileImageUrl?safeImageUrl(p.ProfileImageUrl):'images/person-placeholder.svg';return `<tr><td class="photo-cell"><img class="table-photo" src="${escapeHtml(photo)}" alt="${escapeHtml(nameOf(p))}"></td><td class="icon-cell"><button class="icon-action person-link" data-id="${p.PersonID}" type="button" title="View Person"><img src="images/person.svg" alt=""></button></td><td class="icon-cell"><button class="icon-action tree-link" data-id="${p.PersonID}" type="button" title="View Ancestor Tree"><img src="images/tree.svg" alt=""></button></td><td>${escapeHtml(p.Gender||'')}</td><td class="${isDeceased(p)?'deceased-age':''}">${ageOf(p)}</td><td>${escapeHtml(nameOf(p))}</td></tr>`}
function fill(bodyID,people){const rows=people||[];$(bodyID).innerHTML=rows.length?rows.map(personTableRow).join(''):'<tr><td colspan="6">None entered</td></tr>'}
function wire(){document.querySelectorAll('.person-link').forEach(b=>b.onclick=()=>openPerson(Number(b.dataset.id)));document.querySelectorAll('.tree-link:not(:disabled)').forEach(b=>b.onclick=()=>makeFocus(Number(b.dataset.id)))}
function renderTree(d){const great=[d.maternalGrandmotherMother,d.maternalGrandmotherFather,d.maternalGrandfatherMother,d.maternalGrandfatherFather,d.paternalGrandmotherMother,d.paternalGrandmotherFather,d.paternalGrandfatherMother,d.paternalGrandfatherFather];const grands=[d.maternalGrandmother,d.maternalGrandfather,d.paternalGrandmother,d.paternalGrandfather];const parents=[d.mother,d.father];$('greatGeneration').innerHTML=great.map(x=>card(x)).join('');$('grandGeneration').innerHTML=grands.map(x=>card(x)).join('');$('parentGeneration').innerHTML=parents.map(x=>card(x)).join('');$('focusGeneration').innerHTML=card(d.person,true)}
async function loadAncestor(){const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/ancestor?familyTreeCode=${encodeURIComponent(familyTreeCode)}&cousinGeneration=${encodeURIComponent(cousinGeneration)}`,{headers:authHeaders()}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load family information.');familyTreeCode=d.FamilyTreeCode||familyTreeCode;sessionStorage.setItem('familyTreeCode',familyTreeCode);renderTree(d);$('siblingTitle').textContent=`BIOLOGICAL SIBLINGS (${(d.siblings||[]).length})`;$('partnerTitle').textContent=`PARTNERS (${(d.partners||[]).length})`;$('childTitle').textContent=`BIOLOGICAL CHILDREN (${(d.children||[]).length})`;$('grandchildTitle').textContent=`GRANDCHILDREN (${(d.grandchildren||[]).length})`;$('nephewNieceTitle').textContent=`NEPHEWS AND NIECES (${(d.nephewsNieces||[]).length})`;$('cousinTitle').textContent=`COUSINS (${(d.cousins||[]).length})`;fill('siblingBody',d.siblings);fill('partnerBody',d.partners);fill('childBody',d.children);fill('grandchildBody',d.grandchildren);fill('nephewNieceBody',d.nephewsNieces);fill('cousinBody',d.cousins);wire()}
document.addEventListener('DOMContentLoaded',async()=>{if(!token()){location.href='login.html';return}if(!personID||!familyTreeCode){$('ancestorStatus').textContent='PersonID and FamilyTreeCode are required.';return}$('backBtn').onclick=()=>history.length>1?history.back():location.href=`FTPerson.html?PersonID=${encodeURIComponent(personID)}&familyTreeCode=${encodeURIComponent(familyTreeCode)}`;$('cousinGenerationSelect').value=String(cousinGeneration);$('cousinGenerationSelect').onchange=async()=>{cousinGeneration=Number($('cousinGenerationSelect').value||1);sessionStorage.setItem('familyTreeCousinGeneration',String(cousinGeneration));$('ancestorStatus').textContent='Loading cousins...';try{await loadAncestor();$('ancestorStatus').textContent=''}catch(e){$('ancestorStatus').textContent=e.message}};try{await loadAncestor()}catch(e){$('ancestorStatus').textContent=e.message}});
