const BASE_URL=window.location.hostname==='localhost'&&window.location.port!=='8080'?'http://localhost:8080':window.location.origin;

function escapeHtml(value) {
    return String(value ?? '').replace(/[&<>"']/g, ch => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    })[ch]);
}

function safeImageUrl(value) {
    if (!value) return '';
    try {
        const url = new URL(String(value), window.location.origin);
        return ['http:', 'https:', 'blob:'].includes(url.protocol) ? url.href : '';
    } catch {
        return '';
    }
}
const $=id=>document.getElementById(id),token=()=>localStorage.getItem('token');
const ah=()=>({'Authorization':`Bearer ${token()}`,'Content-Type':'application/json'});
const params=new URLSearchParams(location.search),sourceFamilyTreeCode=params.get('sourceFamilyTreeCode')||'',targetPersonID=Number(params.get('targetPersonID')||0),returnTo=params.get('returnTo')||'person',focalPersonID=Number(params.get('focalPersonID')||0),relationshipKind=params.get('relationshipKind')||'';
let review=null;
const nameOf=p=>[p.LastName?p.LastName+',':'',p.FirstName,p.MiddleName,p.SuffixName].filter(Boolean).join(' ');const names=a=>(a||[]).map(nameOf).join('; ')||'None';
const eventText=e=>[e.EventType,e.EventDate,e.EventPlace].filter(Boolean).join(' — ')+(e.EventDescription?` — ${e.EventDescription}`:'');
const eventsOf=p=>(p.events||[]).length?(p.events||[]).map(e=>`${escapeHtml(e.EventType||'Other')}${e.EventDate?' '+escapeHtml(String(e.EventDate).slice(0,10)):''}${e.EventPlace?' — '+escapeHtml(e.EventPlace):''}`).join('<br>'):'None';
const contactText=c=>`${escapeHtml(c.ContactType||'')}: ${escapeHtml(c.ContactValue||'')}${c.ContactNote?' — '+escapeHtml(c.ContactNote):''}`;
const contactsOf=p=>(p.contacts||[]).length?(p.contacts||[]).map(contactText).join('<br>'):'None';
function personCard(p,label){const profileUrl=safeImageUrl(p.ProfileImageUrl);return `<div class="person-card"><h3>${escapeHtml(label)}</h3><div class="person-top">${profileUrl?`<img src="${escapeHtml(profileUrl)}" alt="">`:''}<div><b>PersonID ${escapeHtml(p.PersonID)}</b><br>${escapeHtml(nameOf(p))}<br>Born: ${escapeHtml(p.BirthDate||'')}<br>Birth Place: ${escapeHtml(p.BirthPlace||'')}<br>Biological Parents: ${escapeHtml(names(p.parents))}<br>Partners: ${escapeHtml(names(p.partners))}<br>Biological Children: ${escapeHtml(names(p.children))}<br><b>Contacts:</b><br>${contactsOf(p)}<br><b>Events:</b><br>${eventsOf(p)}</div></div></div>`}
function renderPictures(group,index,candidate){const all=[...(candidate.images||[]).map(x=>({...x,owner:'older'})),...(group.newerPerson.images||[]).map(x=>({...x,owner:'newer'}))];if(!all.length)return'';return `<div class="pictures">${all.map(img=>{const imageUrl=safeImageUrl(img.url);return `<label class="picture-choice"><input type="checkbox" class="keep-image" data-group="${index}" value="${escapeHtml(img.ImageID)}" checked>${imageUrl?`<img src="${escapeHtml(imageUrl)}" alt="">`:''}<div>${img.owner==='older'?'Older Tree':'Newer Tree'}<br>${escapeHtml(img.ImageType||'')}</div></label>`}).join('')}</div><div class="small">A merged Person may retain no more than five pictures. Uncheck pictures you do not want to keep.</div>`}
function renderConflicts(group,index,candidate){const rows=(candidate.conflicts||[]).map(c=>`<div class="conflict-row"><b>${escapeHtml(c.field)}</b><div>Older: ${escapeHtml(c.olderValue??'')}</div><div>Newer: ${escapeHtml(c.newerValue??'')}</div><select class="conflict-choice" data-group="${index}" data-field="${escapeHtml(c.field)}"><option value="older">Keep Older Tree value</option><option value="newer">Use Newer Tree value</option></select></div>`).join('');return `<div class="conflicts">${rows||'<div class="small">No conflicting populated facts.</div>'}</div>${renderPictures(group,index,candidate)}`}
function render(){const o=review.olderTree,n=review.newerTree;$('olderTreeBox').innerHTML=`<h2>OLDER / AUTHORITATIVE TREE</h2><b>${escapeHtml(o.FamilyTreeCode)}</b><br>Created: ${escapeHtml(String(o.CreatedAt||'').slice(0,10))}`;$('newerTreeBox').innerHTML=`<h2>NEWER TREE TO COMBINE</h2><b>${escapeHtml(n.FamilyTreeCode)}</b><br>Created: ${escapeHtml(String(n.CreatedAt||'').slice(0,10))}`;const groups=review.groups||[];$('noCandidates').classList.toggle('hidden',groups.length>0);$('candidateHost').innerHTML=groups.map((g,i)=>`<div class="person-pair" data-group="${i}"><div class="person-grid">${personCard(g.newerPerson,'Newer Tree Person')}<div class="person-card"><h3>Possible Older Tree Match</h3><select class="match-select" data-group="${i}"><option value="">-- Make a decision --</option><option value="different">DIFFERENT PERSON</option>${g.candidates.map(c=>`<option value="same:${c.PersonID}">SAME PERSON as PersonID ${c.PersonID} — ${escapeHtml(nameOf(c))}</option>`).join('')}</select><div id="candidateDetail${i}" style="margin-top:8px"></div></div></div><div class="decision"><div id="decisionDetail${i}" class="small">Select SAME PERSON or DIFFERENT PERSON.</div></div></div>`).join('');document.querySelectorAll('.match-select').forEach(sel=>sel.onchange=()=>{const i=Number(sel.dataset.group),g=groups[i],host=$(`candidateDetail${i}`);if(sel.value.startsWith('same:')){const id=Number(sel.value.split(':')[1]),c=g.candidates.find(x=>Number(x.PersonID)===id);host.innerHTML=personCard(c,'Selected Older Tree Person')+renderConflicts(g,i,c);$(`decisionDetail${i}`).textContent='These Person records will be combined.'}else if(sel.value==='different'){host.innerHTML='';$(`decisionDetail${i}`).textContent='These records will remain separate people.'}else{host.innerHTML='';$(`decisionDetail${i}`).textContent='Select SAME PERSON or DIFFERENT PERSON.'}})}
async function load(){const r=await fetch(`${BASE_URL}/familytree/one-tree/review?sourceFamilyTreeCode=${encodeURIComponent(sourceFamilyTreeCode)}&targetPersonID=${encodeURIComponent(targetPersonID)}`,{headers:{Authorization:`Bearer ${token()}`}}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load One Tree review.');if(d.alreadySameTree){sessionStorage.setItem('familyTreeCode',d.FamilyTreeCode);location.href=focalPersonID?`FTPerson.html?PersonID=${focalPersonID}&familyTreeCode=${encodeURIComponent(d.FamilyTreeCode)}`:'FamilyTree.html';return}review=d;render()}
function decisions(){const result=[];for(let i=0;i<(review.groups||[]).length;i++){const sel=document.querySelector(`.match-select[data-group="${i}"]`),g=review.groups[i];if(!sel||!sel.value)throw new Error(`Make a Same Person / Different Person decision for newer PersonID ${g.newerPerson.PersonID}.`);if(sel.value==='different'){result.push({newerPersonID:g.newerPerson.PersonID,decision:'different'});continue}const olderPersonID=Number(sel.value.split(':')[1]);const resolutions={};document.querySelectorAll(`.conflict-choice[data-group="${i}"]`).forEach(x=>resolutions[x.dataset.field]=x.value);const keepImageIDs=Array.from(document.querySelectorAll(`.keep-image[data-group="${i}"]:checked`)).map(x=>Number(x.value));if(keepImageIDs.length>5)throw new Error(`PersonID ${g.newerPerson.PersonID}: select no more than five pictures to keep.`);result.push({newerPersonID:g.newerPerson.PersonID,decision:'same',olderPersonID,resolutions,keepImageIDs})}return result}
async function merge(){const ds=decisions();$('mergeBtn').disabled=true;$('status').textContent='Combining FamilyTrees...';const r=await fetch(`${BASE_URL}/familytree/one-tree/merge`,{method:'POST',headers:ah(),body:JSON.stringify({sourceFamilyTreeCode,targetPersonID,decisions:ds,bridge:{focalPersonID:focalPersonID||null,relatedPersonID:targetPersonID,relationshipKind:relationshipKind||null}})}),d=await r.json();if(!r.ok){$('mergeBtn').disabled=false;throw new Error(d.message||'Unable to combine FamilyTrees.')}sessionStorage.setItem('familyTreeCode',d.FamilyTreeCode);$('status').textContent=d.message||'FamilyTrees combined.';const focal=d.focalPersonID||focalPersonID,related=d.relatedPersonID||targetPersonID;if(returnTo==='related'&&focal){const q=new URLSearchParams({PersonID:String(focal),familyTreeCode:d.FamilyTreeCode});if(relationshipKind==='child'&&related)q.set('askPartnerParentChildID',String(related));if(relationshipKind==='partner'&&related)q.set('askPartnerChildrenPersonID',String(related));if(relationshipKind==='sibling'&&related)q.set('askSiblingParentsPersonID',String(related));if((relationshipKind==='mother'||relationshipKind==='father')&&related)q.set('askParentSiblingsPersonID',String(related));location.href=`FTPerson.html?${q.toString()}`}else{location.href=`FTPerson.html?PersonID=${encodeURIComponent(related)}&familyTreeCode=${encodeURIComponent(d.FamilyTreeCode)}`}}
document.addEventListener('DOMContentLoaded',()=>{if(!token()){location.href='login.html';return}const goBack=()=>{if(history.length>1)history.back();else location.href='FamilyTree.html'};$('backBtn').onclick=goBack;$('cancelBtn').onclick=goBack;$('mergeBtn').onclick=()=>merge().catch(e=>$('status').textContent=e.message);load().catch(e=>$('status').textContent=e.message)});
