const BASE_URL=window.location.hostname==='localhost'&&window.location.port!=='8080'?'http://localhost:8080':window.location.origin;
const $=id=>document.getElementById(id),token=()=>localStorage.getItem('token'),ah=(j=true)=>{const h={Authorization:`Bearer ${token()}`};if(j)h['Content-Type']='application/json';return h};
let personID=null,code=sessionStorage.getItem('familyTreeCode')||'',activeRel='',saved=false,mainDifferent=new Set(),relatedDifferent=new Set();
const nv=v=>String(v||'').trim()||null;const nameOf=p=>[p.LastName?p.LastName+',':'',p.FirstName,p.MiddleName,p.SuffixName].filter(Boolean).join(' ');const shortNames=a=>(a||[]).map(nameOf).filter(Boolean).join('; ')||'None';
function pData(prefix=''){return{FirstName:nv($(prefix+'FirstName').value),MiddleName:nv($(prefix+'MiddleName').value),LastName:nv($(prefix+'LastName').value),SuffixName:nv($(prefix+'SuffixName').value),NickName:nv($(prefix+'NickName').value),MaidenName:nv($(prefix+'MaidenName').value),Gender:nv($(prefix+'Gender').value),BirthDate:nv($(prefix+'BirthDate').value),BirthPlace:nv($(prefix+'BirthPlace').value)}}
function mainData(){const p=pData('');return{...p,Died:$('Died').checked?1:0,DeathDate:$('Died').checked?nv($('DeathDate').value):null,familyTreeCode:code||null}}
function duplicateQuery(p){const qs=new URLSearchParams();['FirstName','MiddleName','LastName','BirthDate','BirthPlace','MaidenName','Gender','DeathDate'].forEach(k=>{if(p[k])qs.set(k,p[k])});if(p.Died)qs.set('Died','1');return qs}
function oneTreeRedirect(existingID,related){const q=new URLSearchParams({sourceFamilyTreeCode:code,targetPersonID:String(existingID),returnTo:related?'related':'person'});if(related&&personID){q.set('focalPersonID',String(personID));q.set('relationshipKind',activeRel)}location.href=`FTOneTreeMerge.html?${q.toString()}`}
function renderDuplicates(rows,body,wrap,status,differentSet,related=false){wrap.classList.toggle('hidden',!rows.length);body.innerHTML=rows.map(x=>`<tr data-dup-id="${x.PersonID}"><td>${x.ProfileImageUrl?`<img class="dup-photo" src="${x.ProfileImageUrl}" alt="">`:''}</td><td><button type="button" class="view-existing" data-id="${x.PersonID}">${x.PersonID}</button></td><td>${nameOf(x)}</td><td>${x.BirthDate||''}</td><td>${x.BirthPlace||''}</td><td>${shortNames(x.parents)}</td><td>${shortNames(x.partners)}</td><td>${shortNames(x.children)}</td><td>${x.FamilyTreeCode||x.OldestFamilyTreeCode||''}</td><td>${(x.MatchReasons||[]).join(', ')}</td><td><button type="button" class="use-existing" data-id="${x.PersonID}">USE THIS PERSON</button> <button type="button" class="different-person" data-id="${x.PersonID}">${differentSet.has(Number(x.PersonID))?'MARKED DIFFERENT':'THIS IS A DIFFERENT PERSON'}</button></td></tr>`).join('');status.textContent=rows.length?`${rows.length} possible duplicate(s) found. Review each possible match before creating a new Person.`:'No possible duplicates found.';body.querySelectorAll('.view-existing').forEach(b=>b.onclick=()=>window.open(`FTPersonDuplicate.html?PersonID=${encodeURIComponent(b.dataset.id)}`,'_blank'));body.querySelectorAll('.use-existing').forEach(b=>b.onclick=()=>useExisting(Number(b.dataset.id),related).catch(e=>status.textContent=e.message));body.querySelectorAll('.different-person').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.id);differentSet.add(id);b.textContent='MARKED DIFFERENT';b.disabled=true;status.textContent='Marked as a different person. Press SAVE again after reviewing all possible duplicates.'})}
async function duplicates(p,body,wrap,status,differentSet,related=false){if(!p.FirstName&&!p.LastName&&!p.BirthDate){status.textContent='Enter a name or birth date first.';return[]}const r=await fetch(`${BASE_URL}/familytree/persons/duplicates?${duplicateQuery(p)}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Duplicate search failed');const rows=d.matches||[];renderDuplicates(rows,body,wrap,status,differentSet,related);return rows}
async function useExisting(existingID,related){const body={personID:existingID,familyTreeCode:code||null};if(related){body.focalPersonID=personID;body.relationshipKind=activeRel}const r=await fetch(`${BASE_URL}/familytree/use-existing-person`,{method:'POST',headers:ah(),body:JSON.stringify(body)}),d=await r.json();if(r.status===409&&d.code==='ONE_TREE_REVIEW_REQUIRED')return oneTreeRedirect(existingID,related);if(!r.ok)throw new Error(d.message||'Unable to use existing person');code=d.FamilyTreeCode;sessionStorage.setItem('familyTreeCode',code);$('familyTreeCodeDisplay').textContent=code;if(related){$('relatedModal').classList.remove('show');await loadRel();$('statusMessage').textContent=`Existing person added. Current FamilyTreeCode updated to ${code}.`}else{location.href=`FTPerson.html?PersonID=${existingID}&familyTreeCode=${encodeURIComponent(code)}`}}
async function loadRel(){const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/relationships?familyTreeCode=${encodeURIComponent(code)}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load relationships');$('motherList').textContent=(d.mother||[]).map(nameOf).join('; ')||'None';$('fatherList').textContent=(d.father||[]).map(nameOf).join('; ')||'None';$('partnerList').textContent=(d.partners||[]).map(nameOf).join('; ')||'None';$('childList').textContent=(d.children||[]).map(nameOf).join('; ')||'None'}
function clearRelated(){['FirstName','MiddleName','LastName','SuffixName','NickName','MaidenName','BirthDate','BirthPlace'].forEach(k=>$('r'+k).value='');$('rGender').value='';$('rDupWrap').classList.add('hidden');$('rDupBody').innerHTML='';$('rStatus').textContent='';relatedDifferent=new Set()}
async function saveRelated(){const p=pData('r');if(!p.FirstName&&!p.LastName)return $('rStatus').textContent='Enter First Name or Last Name.';const r=await fetch(`${BASE_URL}/familytree/related-person`,{method:'POST',headers:ah(),body:JSON.stringify({...p,familyTreeCode:code,focalPersonID:personID,relationshipKind:activeRel,confirmedDifferentPersonIDs:[...relatedDifferent]})}),d=await r.json();if(r.status===409&&d.code==='DUPLICATE_REVIEW_REQUIRED'){renderDuplicates(d.matches||[],$('rDupBody'),$('rDupWrap'),$('rStatus'),relatedDifferent,true);return}if(!r.ok)throw new Error(d.message||'Unable to save relative');$('relatedModal').classList.remove('show');await loadRel();$('statusMessage').textContent=`${activeRel} saved.`}
document.addEventListener('DOMContentLoaded',()=>{if(!token()){location.href='login.html';return}$('familyTreeCodeDisplay').textContent=code||'New code will be assigned when saved';$('Died').onchange=()=>{$('DeathDate').disabled=!$('Died').checked};$('checkDuplicatesBtn').onclick=()=>duplicates(mainData(),$('duplicateBody'),$('duplicateSection'),$('statusMessage'),mainDifferent,false).catch(e=>$('statusMessage').textContent=e.message);$('clearBtn').onclick=()=>{if(saved)return;$('personForm').reset();$('duplicateSection').classList.add('hidden');mainDifferent=new Set()};
$('personForm').onsubmit=async e=>{e.preventDefault();if(saved)return;const p=mainData();if(!p.FirstName&&!p.LastName)return $('statusMessage').textContent='Enter First Name or Last Name.';$('savePersonBtn').disabled=true;const r=await fetch(`${BASE_URL}/familytree/persons`,{method:'POST',headers:ah(),body:JSON.stringify({...p,confirmedDifferentPersonIDs:[...mainDifferent]})}),d=await r.json();if(r.status===409&&d.code==='DUPLICATE_REVIEW_REQUIRED'){$('savePersonBtn').disabled=false;renderDuplicates(d.matches||[],$('duplicateBody'),$('duplicateSection'),$('statusMessage'),mainDifferent,false);return}if(!r.ok){$('savePersonBtn').disabled=false;return $('statusMessage').textContent=d.message||'Save failed'}saved=true;personID=d.PersonID;code=d.FamilyTreeCode;sessionStorage.setItem('familyTreeCode',code);$('personIDDisplay').textContent=personID;$('familyTreeCodeDisplay').textContent=code;$('savePersonBtn').style.display='none';$('clearBtn').style.display='none';document.querySelectorAll('#personForm input,#personForm select').forEach(x=>x.disabled=true);$('part2Section').classList.remove('hidden');$('statusMessage').textContent='Person saved. Part 2 actions save independently.';await loadRel()};
document.querySelectorAll('[data-addrel]').forEach(b=>b.onclick=()=>{activeRel=b.dataset.addrel;clearRelated();$('relatedTitle').textContent='ADD '+activeRel.toUpperCase();$('relatedModal').classList.add('show')});$('rCloseBtn').onclick=()=> $('relatedModal').classList.remove('show');$('rCheckBtn').onclick=()=>duplicates(pData('r'),$('rDupBody'),$('rDupWrap'),$('rStatus'),relatedDifferent,true).catch(e=>$('rStatus').textContent=e.message);$('rSaveBtn').onclick=()=>saveRelated().catch(e=>$('rStatus').textContent=e.message);
$('uploadProfileBtn').onclick=async()=>{const f=$('profileImage').files[0];if(!f)return $('profileStatus').textContent='Select a picture.';const upload=async replace=>{const fd=new FormData();fd.append('profileImage',f);fd.append('familyTreeCode',code);if(replace)fd.append('replaceProfile','1');const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/profile-image`,{method:'POST',headers:{Authorization:`Bearer ${token()}`},body:fd}),d=await r.json();if(r.status===409&&!replace){if(confirm('A profile picture already exists for this PersonID. Replace it?'))return upload(true);$('profileStatus').textContent='Picture was not replaced.';return}if(!r.ok)throw new Error(d.message||'Picture upload failed');$('profileStatus').textContent='Profile picture saved.'};upload(false).catch(e=>$('profileStatus').textContent=e.message)};
$('addEventBtn').onclick=async()=>{const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/events`,{method:'POST',headers:ah(),body:JSON.stringify({familyTreeCode:code,eventType:nv($('EventType').value)||'Other',eventDate:nv($('EventDate').value),eventPlace:nv($('EventPlace').value),eventDescription:nv($('EventDescription').value)})}),d=await r.json();$('eventStatus').textContent=r.ok?'Event saved.':(d.message||'Event save failed.')};
});
