const BASE_URL=window.location.hostname==='localhost'&&window.location.port!=='8080'?'http://localhost:8080':window.location.origin;
const $=id=>document.getElementById(id),token=()=>localStorage.getItem('token'),ah=(j=true)=>{const h={Authorization:`Bearer ${token()}`};if(j)h['Content-Type']='application/json';return h};
let personID=null,code=sessionStorage.getItem('familyTreeCode')||'',activeRel='',saved=false;
const nv=v=>String(v||'').trim()||null;const nameOf=p=>[p.LastName?p.LastName+',':'',p.FirstName,p.MiddleName,p.SuffixName].filter(Boolean).join(' ');
function pData(prefix=''){return{FirstName:nv($(prefix+'FirstName').value),MiddleName:nv($(prefix+'MiddleName').value),LastName:nv($(prefix+'LastName').value),SuffixName:nv($(prefix+'SuffixName').value),NickName:nv($(prefix+'NickName').value),MaidenName:nv($(prefix+'MaidenName').value),Gender:nv($(prefix+'Gender').value),BirthDate:nv($(prefix+'BirthDate').value),BirthPlace:nv($(prefix+'BirthPlace').value)}}
function mainData(){const p=pData('');return{...p,Died:$('Died').checked?1:0,DeathDate:$('Died').checked?nv($('DeathDate').value):null,familyTreeCode:code||null}}
async function duplicates(p,body,wrap,status,related=false){const qs=new URLSearchParams();['FirstName','LastName','BirthDate','BirthPlace','MaidenName'].forEach(k=>{if(p[k])qs.set(k,p[k])});if(!p.FirstName&&!p.LastName&&!p.BirthDate){status.textContent='Enter a name or birth date first.';return}const r=await fetch(`${BASE_URL}/familytree/persons/duplicates?${qs}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Duplicate search failed');const rows=d.matches||[];wrap.classList.toggle('hidden',!rows.length);body.innerHTML=rows.map(x=>`<tr><td>${x.PersonID}</td><td>${nameOf(x)}</td><td>${x.BirthDate||''}</td><td>${x.BirthPlace||''}</td><td>${x.OldestFamilyTreeCode||''}</td><td><button class="use-existing" data-id="${x.PersonID}">USE THIS PERSON</button></td></tr>`).join('');status.textContent=rows.length?`${rows.length} possible duplicate(s) found.`:'No possible duplicates found.';document.querySelectorAll('.use-existing').forEach(b=>b.onclick=()=>useExisting(Number(b.dataset.id),related))}
async function useExisting(existingID,related){const body={personID:existingID};if(related){body.focalPersonID=personID;body.relationshipKind=activeRel}const r=await fetch(`${BASE_URL}/familytree/use-existing-person`,{method:'POST',headers:ah(),body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to use existing person');code=d.FamilyTreeCode;sessionStorage.setItem('familyTreeCode',code);$('familyTreeCodeDisplay').textContent=code;if(related){$('relatedModal').classList.remove('show');await loadRel();$('statusMessage').textContent=`Existing person added. Current FamilyTreeCode updated to ${code}.`}else{location.href=`FTPerson.html?PersonID=${existingID}&familyTreeCode=${encodeURIComponent(code)}`}}
async function loadRel(){const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/relationships?familyTreeCode=${encodeURIComponent(code)}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load relationships');$('motherList').textContent=(d.mother||[]).map(nameOf).join('; ')||'None';$('fatherList').textContent=(d.father||[]).map(nameOf).join('; ')||'None';$('partnerList').textContent=(d.partners||[]).map(nameOf).join('; ')||'None';$('childList').textContent=(d.children||[]).map(nameOf).join('; ')||'None'}
function clearRelated(){['FirstName','MiddleName','LastName','SuffixName','NickName','MaidenName','BirthDate','BirthPlace'].forEach(k=>$('r'+k).value='');$('rGender').value='';$('rDupWrap').classList.add('hidden');$('rStatus').textContent=''}
async function saveRelated(){const p=pData('r');if(!p.FirstName&&!p.LastName)return $('rStatus').textContent='Enter First Name or Last Name.';const r=await fetch(`${BASE_URL}/familytree/related-person`,{method:'POST',headers:ah(),body:JSON.stringify({...p,familyTreeCode:code,focalPersonID:personID,relationshipKind:activeRel})}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to save relative');$('relatedModal').classList.remove('show');await loadRel();$('statusMessage').textContent=`${activeRel} saved.`}
document.addEventListener('DOMContentLoaded',()=>{if(!token()){location.href='login.html';return}$('familyTreeCodeDisplay').textContent=code||'New code will be assigned when saved';$('Died').onchange=()=>{$('DeathDate').disabled=!$('Died').checked};$('checkDuplicatesBtn').onclick=()=>duplicates(mainData(),$('duplicateBody'),$('duplicateSection'),$('statusMessage'),false).catch(e=>$('statusMessage').textContent=e.message);$('clearBtn').onclick=()=>{if(saved)return;$('personForm').reset();$('duplicateSection').classList.add('hidden')};
$('personForm').onsubmit=async e=>{e.preventDefault();if(saved)return;const p=mainData();if(!p.FirstName&&!p.LastName)return $('statusMessage').textContent='Enter First Name or Last Name.';$('savePersonBtn').disabled=true;const r=await fetch(`${BASE_URL}/familytree/persons`,{method:'POST',headers:ah(),body:JSON.stringify(p)}),d=await r.json();if(!r.ok){$('savePersonBtn').disabled=false;return $('statusMessage').textContent=d.message||'Save failed'}saved=true;personID=d.PersonID;code=d.FamilyTreeCode;sessionStorage.setItem('familyTreeCode',code);$('personIDDisplay').textContent=personID;$('familyTreeCodeDisplay').textContent=code;$('savePersonBtn').style.display='none';$('clearBtn').style.display='none';document.querySelectorAll('#personForm input,#personForm select').forEach(x=>x.disabled=true);$('part2Section').classList.remove('hidden');$('statusMessage').textContent='Person saved. Part 2 actions save independently.';await loadRel()};
document.querySelectorAll('[data-addrel]').forEach(b=>b.onclick=()=>{activeRel=b.dataset.addrel;clearRelated();$('relatedTitle').textContent='ADD '+activeRel.toUpperCase();$('relatedModal').classList.add('show')});$('rCloseBtn').onclick=()=> $('relatedModal').classList.remove('show');$('rCheckBtn').onclick=()=>duplicates(pData('r'),$('rDupBody'),$('rDupWrap'),$('rStatus'),true).catch(e=>$('rStatus').textContent=e.message);$('rSaveBtn').onclick=()=>saveRelated().catch(e=>$('rStatus').textContent=e.message);
$('uploadProfileBtn').onclick=async()=>{const f=$('profileImage').files[0];if(!f)return $('profileStatus').textContent='Select a picture.';const upload=async replace=>{const fd=new FormData();fd.append('profileImage',f);fd.append('familyTreeCode',code);if(replace)fd.append('replaceProfile','1');const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/profile-image`,{method:'POST',headers:{Authorization:`Bearer ${token()}`},body:fd}),d=await r.json();if(r.status===409&&!replace){if(confirm('A profile picture already exists for this PersonID. Replace it?'))return upload(true);$('profileStatus').textContent='Picture was not replaced.';return}if(!r.ok)throw new Error(d.message||'Picture upload failed');$('profileStatus').textContent='Profile picture saved.'};upload(false).catch(e=>$('profileStatus').textContent=e.message)};
$('addEventBtn').onclick=async()=>{const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/events`,{method:'POST',headers:ah(),body:JSON.stringify({familyTreeCode:code,eventType:nv($('EventType').value)||'Other',eventDate:nv($('EventDate').value),eventPlace:nv($('EventPlace').value),eventDescription:nv($('EventDescription').value)})}),d=await r.json();$('eventStatus').textContent=r.ok?'Event saved.':(d.message||'Event save failed.')};
});