const BASE_URL=window.location.hostname==='localhost'&&window.location.port!=='8080'?'http://localhost:8080':window.location.origin;
const $=id=>document.getElementById(id),token=()=>localStorage.getItem('token'),ah=(j=true)=>{const h={Authorization:`Bearer ${token()}`};if(j)h['Content-Type']='application/json';return h};
const q=new URLSearchParams(location.search);const personID=Number(q.get('PersonID'));let familyTreeCode=q.get('familyTreeCode')||sessionStorage.getItem('familyTreeCode')||'',activeRel='';
function ageOf(p){if(!p.BirthDate)return'';const s=new Date(p.BirthDate+'T00:00:00'),e=p.DeathDate?new Date(p.DeathDate+'T00:00:00'):new Date();let a=e.getFullYear()-s.getFullYear(),m=e.getMonth()-s.getMonth();if(m<0||(m===0&&e.getDate()<s.getDate()))a--;return a>=0?a:''}
function nameOf(p){const g=[p.FirstName,p.MiddleName,p.SuffixName].filter(Boolean).join(' ');let n=[p.LastName?`${p.LastName},`:'',g].filter(Boolean).join(' ').trim();const x=[p.NickName,p.MaidenName].filter(Boolean).join(' ');if(x)n+=` (${x})`;return n||`Person ${p.PersonID}`}
function dateUS(v){if(!v)return'';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[1]}/${p[2]}/${p[0]}`:v}
function row(p,extra=[]){return `<tr><td><button class="plink" data-id="${p.PersonID}">${p.PersonID}</button></td><td>${p.Gender||''}</td><td>${ageOf(p)}</td><td>${p.FirstName||''}</td><td>${p.MiddleName||''}</td><td>${p.LastName||''}</td><td>${p.SuffixName||''}</td><td>${p.NickName||''}</td><td>${p.MaidenName||''}</td>${extra.map(x=>`<td>${x||''}</td>`).join('')}</tr>`}
function wire(){document.querySelectorAll('.plink').forEach(b=>b.onclick=()=>location.href=`FTPerson.html?PersonID=${b.dataset.id}&familyTreeCode=${encodeURIComponent(familyTreeCode)}`)}
async function loadPerson(){const r=await fetch(`${BASE_URL}/familytree/persons/${personID}?familyTreeCode=${encodeURIComponent(familyTreeCode)}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load person');const p=d.person;familyTreeCode=d.FamilyTreeCode||familyTreeCode;sessionStorage.setItem('familyTreeCode',familyTreeCode);['PersonID','Gender','FirstName','MiddleName','LastName','SuffixName','NickName','MaidenName','BirthPlace'].forEach(k=>$(k).textContent=p[k]||'');$('BirthDate').textContent=dateUS(p.BirthDate);$('DeathDate').textContent=dateUS(p.DeathDate);$('Age').textContent=ageOf(p);$('Died').textContent=Number(p.Died)?'Yes':'No';$('FamilyTreeCode').textContent=familyTreeCode}
async function loadRel(){const r=await fetch(`${BASE_URL}/familytree/persons/${personID}/relationships?familyTreeCode=${encodeURIComponent(familyTreeCode)}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load relationships');const pa=[...(d.mother||[]),...(d.father||[])];$('parentBody').innerHTML=pa.length?pa.map(p=>row(p,[p.ParentType,p.AncestrySide])).join(''):'<tr><td colspan="11">None entered</td></tr>';$('partnerBody').innerHTML=(d.partners||[]).length?d.partners.map(p=>row(p)).join(''):'<tr><td colspan="9">None entered</td></tr>';$('childBody').innerHTML=(d.children||[]).length?d.children.map(p=>row(p)).join(''):'<tr><td colspan="9">None entered</td></tr>';wire()}
async function loadImages(){let r=await fetch(`${BASE_URL}/familytree/persons/${personID}/profile-image?familyTreeCode=${encodeURIComponent(familyTreeCode)}`,{headers:ah(false)});if(r.ok){const d=await r.json();$('profileImage').src=d.url+'?v='+Date.now()}else $('profileImage').removeAttribute('src');r=await fetch(`${BASE_URL}/familytree/persons/${personID}/life-images?familyTreeCode=${encodeURIComponent(familyTreeCode)}`,{headers:ah(false)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to load life images');const rows=d.images||[],h=$('lifeStrip');h.innerHTML='';for(let i=1;i<=4;i++){const im=rows.find(x=>Number(x.SortOrder)===i),c=document.createElement('div');c.className='life-card';c.innerHTML=im?`<img src="${im.url}?v=${Date.now()}"><div>${im.Caption||''}</div><div class="small">${im.ApproxAge!=null?'Approx. age '+im.ApproxAge:''}</div>`:`<div class="small">Image ${i}<br>Not entered</div>`;h.appendChild(c)}}
const rv=id=>$(id).value.trim()||null;function rdata(){return{FirstName:rv('rFirstName'),MiddleName:rv('rMiddleName'),LastName:rv('rLastName'),SuffixName:rv('rSuffixName'),NickName:rv('rNickName'),MaidenName:rv('rMaidenName'),Gender:$('rGender').value||null,BirthDate:$('rBirthDate').value||null,BirthPlace:rv('rBirthPlace')}}
function clearR(){['rFirstName','rMiddleName','rLastName','rSuffixName','rNickName','rMaidenName','rBirthDate','rBirthPlace'].forEach(i=>$(i).value='');$('rGender').value='';$('rDupWrap').classList.add('hidden');$('rDupBody').innerHTML='';$('rStatus').textContent=''}
async function dup(){const p=rdata(),s=new URLSearchParams();['FirstName','LastName','BirthDate','BirthPlace','MaidenName'].forEach(k=>{if(p[k])s.set(k,p[k])});if(!p.FirstName&&!p.LastName&&!p.BirthDate){$('rStatus').textContent='Enter a name or birth date first.';return}const r=await fetch(`${BASE_URL}/familytree/persons/duplicates?${s}`,{headers:ah(false)}),d=await r.json();if(!r.ok)throw new Error(d.message||'Duplicate check failed');$('rDupWrap').classList.toggle('hidden',!(d.matches||[]).length);$('rDupBody').innerHTML=(d.matches||[]).map(x=>`<tr><td>${x.PersonID}</td><td>${nameOf(x)}</td><td>${dateUS(x.BirthDate)}</td><td>${x.BirthPlace||''}</td><td>${x.OldestFamilyTreeCode||''}</td><td><button class="usex" data-id="${x.PersonID}">USE EXISTING</button></td></tr>`).join('');$('rStatus').textContent=(d.matches||[]).length?`${d.matches.length} possible duplicate(s) found.`:'No possible duplicates found.';document.querySelectorAll('.usex').forEach(b=>b.onclick=()=>useExisting(Number(b.dataset.id)))}
async function useExisting(id){const r=await fetch(`${BASE_URL}/familytree/relationships`,{method:'POST',headers:ah(),body:JSON.stringify({familyTreeCode,focalPersonID:personID,relatedPersonID:id,relationshipKind:activeRel})}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to create relationship');$('relatedModal').classList.remove('show');await loadRel()}
async function saveRelated(){const p=rdata();if(!p.FirstName&&!p.LastName){$('rStatus').textContent='Enter First Name or Last Name.';return}const r=await fetch(`${BASE_URL}/familytree/related-person`,{method:'POST',headers:ah(),body:JSON.stringify({...p,familyTreeCode,focalPersonID:personID,relationshipKind:activeRel})}),d=await r.json();if(!r.ok)throw new Error(d.message||'Unable to save related person');$('relatedModal').classList.remove('show');await loadRel()}
document.addEventListener('DOMContentLoaded',async()=>{if(!token()){location.href='login.html';return}if(!personID||!familyTreeCode){$('pageStatus').textContent='PersonID and FamilyTreeCode are required.';return}try{await loadPerson();await Promise.all([loadRel(),loadImages()])}catch(e){$('pageStatus').textContent=e.message}
document.querySelectorAll('[data-addrel]').forEach(b=>b.onclick=()=>{activeRel=b.dataset.addrel;clearR();$('relatedTitle').textContent='ADD '+activeRel.toUpperCase();$('relatedModal').classList.add('show')});$('rCloseBtn').onclick=()=> $('relatedModal').classList.remove('show');$('rCheckBtn').onclick=()=>dup().catch(e=>$('rStatus').textContent=e.message);$('rSaveBtn').onclick=()=>saveRelated().catch(e=>$('rStatus').textContent=e.message);$('editBtn').onclick=()=>alert('Edit Person will be added after the FTPerson display workflow is tested.');$('eventBtn').onclick=()=>alert('The dedicated Event workflow will be connected next.');$('contactBtn').onclick=()=>alert('Contact page will be added in the next FamilyTree stage.');$('ancestorBtn').onclick=()=>alert('Ancestor page will be added in the next FamilyTree stage.');$('deleteBtn').onclick=async()=>{if(!confirm('Delete this person from the current Family Tree?'))return;const r=await fetch(`${BASE_URL}/familytree/persons/${personID}?familyTreeCode=${encodeURIComponent(familyTreeCode)}`,{method:'DELETE',headers:ah(false)}),d=await r.json();if(!r.ok)return alert(d.message||'Delete failed');alert(d.message);location.href='FTPersonList.html'}})